// Copyright (c) 2026 Charis Chakim - Undagi (https://github.com/CharisChakim/undagi)
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

import type { ProjectSession } from "../types";

// Satu generator dipakai semua ekspor agar AGENTS.md tidak berubah tergantung
// tombol atau layar mana yang dipakai pengguna.
export function buildAgentsMarkdown(session: ProjectSession): string {
  const titleStr = session.input.title || session.title || "AI PROJECT";
  const tasks = session.tasks || [];
  let md = `# AI AGENT EXECUTION TASKS: ${titleStr.toUpperCase()}\n\n`;
  md += `> Generated by Undagi on ${new Date().toLocaleDateString()}\n`;
  md += `> Target System: AI Coding Agent (Cursor, Antigravity Agent, Gemini, Claude Code)\n\n`;
  md += `## RULES FOR AI AGENT EXECUTION\n`;
  md += `1. Work through the tasks in ID order (TASK-01, TASK-02, ...).\n`;
  md += `2. Always read the target file before editing it, to avoid conflicts.\n`;
  md += `3. Run the verification at the end of each task before moving on.\n\n`;
  md += `===================================================\n\n`;

  tasks.forEach((task) => {
    md += `### [${task.id}] ${task.title} (${(task.status || "todo").toUpperCase()})\n`;
    md += `- **Phase**: ${task.phase || "Development"}\n`;
    md += `- **Priority**: ${task.priority}\n`;
    md += `- **Target files**: \`${(task.targetFiles || []).join("`, `")}\` \n`;
    md += `- **Dependencies**: ${(task.dependencies || []).length > 0 ? task.dependencies.join(", ") : "None"}\n\n`;
    md += `#### AI agent prompt:\n\`\`\`\n${task.promptInstructions}\n\`\`\`\n\n`;
    md += `#### Verification steps:\n${task.verificationSteps}\n\n`;
    md += `===================================================\n\n`;
  });

  return md;
}

export function agentsMarkdownFilename(session: ProjectSession): string {
  const slug = (session.input.title || session.title || "project").toLowerCase().replace(/[^a-z0-9]/g, "_");
  return `AGENTS_${slug}.md`;
}
